[versions]
ktor = "3.3.0"

[libraries]
serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml", version.ref = "ktor" }
server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
server-contentnegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version.ref = "ktor" }

[plugins]
plugin = { id = "io.ktor.plugin", version.ref = "ktor" }
